### ISSUE TITLE
blocking the correct site

### ISSUE THREAD

**Issue by Miklesp** [betafish-inc/adblock-windows#1]
Hi! My site is an advertising agency in the city of Krasnodar. My site name [adspace.pro](https://adspace.pro/) falls under the filter. There are also subdomains for individual directions, for example [outdoor.adspace.pro](https://outdoor.adspace.pro/) . This name also falls under your filters. I ask you to exclude my site from the list of filters so that users do not have problems viewing my site in the future.

**Comment by badslug** [comment]
Hi, this repository is not part of, or related to our ad blocking extension. For support for AdBlock please visit https://help.getadblock.com/support/home
